#!/bin/bash

# compile locationparser
if [ ! -f locationparser/target/locationparser/bin/run ]; then
  cd locationparser && mvn package
  cd target && tar -xzf locationparser-1.0-SNAPSHOT-dist.tar.gz
  cd ../../
fi

# start locationparser in background and wait 5 secs
locationparser/target/locationparser/bin/run &
pid=$!
sleep 5

# start collecting data
python collect/collect.py config.json gharchive/query-results.csv

# stop locationparser
kill $pid
